# Generate Makefiles using CMake
generate:
	@echo "Generating Makefiles..."
	CXX=clang++ CC=clang cmake -B build/
	ln -sf build/compile_commands.json compile_commands.json
	@echo "Done!"

# Build the project
build: generate
	@echo "Building project..."
	cmake --build build/
	@echo "Done!"

# Run tests for the project, or for a specific target. The default is to run all tests.
test target=".*Test":
	@echo "Running tests for {{target}}..."
	ctest --test-dir ./build -R {{target}}
	@echo "Done!"

# Clean the project
clean:
	@echo "Cleaning project..."
	rm -rf build/
	rm -f compile_commands.json
	@echo "Done!"
