name: C#

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - name: Restore dependencies
        run: dotnet restore
        working-directory: CSharp

      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage;Format=lcov" -l "console;verbosity=normal"
        working-directory: CSharp

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
