name: Dog

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: Golang/go.sum

      - name: Test
        run: go test -cover -race -coverprofile=coverage.txt -covermode=atomic ./...
        working-directory: Golang

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
