name: JavaScript

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Test
        run: npm run test
        working-directory: JavaScript
