name: Java

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test
        run: ./gradlew test
        working-directory: Java
